"""docs/08-testing.md's `test_ingest_pipeline` + docs/10-roadmap.md's Phase 3 exit criteria.
Runs against the real deployed `dev` stack — `CWD_INTEGRATION=1 uv run pytest -m integration`
(see `conftest.py` for the env vars it needs).

Asserts `READY`, chunk count, and one hand-checked sentence's rect — **not** vector count. Phase
3's explicit goal is "no embeddings yet" (docs/10-roadmap.md's Phase 3 header); the vector-count
assertion docs/08-testing.md's table describes belongs to this same test's Phase 4 revision, once
`EnsureIndex`/`EmbedAndIndex` exist.
"""

from __future__ import annotations

import json
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest

if TYPE_CHECKING:
    from conftest import CognitoConfig

    from common.repo import Repo

pytestmark = pytest.mark.integration

_FIXTURES = Path(__file__).resolve().parents[4] / "e2e" / "fixtures"

# Hand-checked against e2e/fixtures/five-page.pdf (generated by
# e2e/fixtures/generate_fixtures.py's five_page_pdf): page 3's second sentence, computed by
# running services/ingestion/ingestion/{extract,chunk}.py directly against the fixture and
# reading off the result — see docs/10-roadmap.md's Phase 3 progress log entry for the exact
# derivation.
_EXPECTED_PAGE = 3
_EXPECTED_SENTENCE_TEXT = (
    "Energy consumption per square foot fell to its lowest level since the facility opened."
)
_EXPECTED_RECT = (127.33, 153.29, 471.18, 165.66)
_RECT_TOLERANCE_PT = 1.0


def _request(
    method: str, url: str, *, token: str, body: dict[str, Any] | None = None
) -> tuple[int, dict[str, Any]]:
    data = json.dumps(body).encode() if body is not None else None
    request = urllib.request.Request(
        url,
        data=data,
        method=method,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request) as response:  # noqa: S310
            return response.status, json.loads(response.read())
    except urllib.error.HTTPError as error:
        return error.code, json.loads(error.read())


def _upload_fixture(
    cognito_config: CognitoConfig, token: str, filename: str, content_type: str
) -> tuple[str, str]:
    data = (_FIXTURES / filename).read_bytes()
    status, body = _request(
        "POST",
        f"{cognito_config.api_base_url}/projects",
        token=token,
        body={"name": f"cwd-integration-ingest-{filename}"},
    )
    assert status == 201, body
    project_id: str = body["projectId"]

    status, body = _request(
        "POST",
        f"{cognito_config.api_base_url}/projects/{project_id}/documents",
        token=token,
        body={"filename": filename, "contentType": content_type, "byteSize": len(data)},
    )
    assert status == 201, body
    document_id: str = body["document"]["documentId"]

    upload = body["upload"]
    put_request = urllib.request.Request(
        upload["url"], data=data, method="PUT", headers=upload["headers"]
    )
    with urllib.request.urlopen(put_request) as response:  # noqa: S310
        assert response.status == 200
    return project_id, document_id


def _wait_for_terminal_status(
    cognito_config: CognitoConfig,
    token: str,
    project_id: str,
    document_id: str,
    *,
    timeout_s: float = 180.0,
) -> dict[str, Any]:
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        status, body = _request(
            "GET",
            f"{cognito_config.api_base_url}/projects/{project_id}/documents/{document_id}",
            token=token,
        )
        assert status == 200, body
        if body["status"] in ("READY", "FAILED"):
            return body
        time.sleep(5)
    pytest.fail(f"document {document_id} did not reach a terminal status within {timeout_s}s")


def test_ingest_pipeline_reaches_ready_with_expected_chunks_and_a_hand_checked_rect(
    cognito_config: CognitoConfig, seeded_user_token: str, repo: Repo
) -> None:
    project_id, document_id = _upload_fixture(
        cognito_config, seeded_user_token, "five-page.pdf", "application/pdf"
    )
    try:
        status, body = _request(
            "POST",
            f"{cognito_config.api_base_url}/projects/{project_id}/documents/{document_id}/ingest",
            token=seeded_user_token,
        )
        assert status == 202, body

        document = _wait_for_terminal_status(
            cognito_config, seeded_user_token, project_id, document_id
        )
        assert document["status"] == "READY", document.get("statusDetail")
        assert document["pageCount"] == 5
        assert document["ingestion"]["chunkCount"] > 0
        assert document["ingestion"]["ocrPages"] == 0

        pages = repo.list_pages(document_id)
        assert len(pages) == 5
        assert all(p.text_source == "pdf" for p in pages)

        chunks = [c for c in repo.list_chunks(document_id) if c.page_number == _EXPECTED_PAGE]
        assert chunks, f"no chunks found for page {_EXPECTED_PAGE}"
        matching_sentence = next(
            (
                sentence
                for chunk in chunks
                for sentence in chunk.sentences
                if sentence.text == _EXPECTED_SENTENCE_TEXT
            ),
            None,
        )
        assert matching_sentence is not None, (
            f"expected sentence not found among page {_EXPECTED_PAGE}'s chunks"
        )
        assert len(matching_sentence.rects) == 1
        rect = matching_sentence.rects[0]
        for actual, expected in zip(rect, _EXPECTED_RECT, strict=True):
            assert actual == pytest.approx(expected, abs=_RECT_TOLERANCE_PT)
    finally:
        _request(
            "DELETE",
            f"{cognito_config.api_base_url}/projects/{project_id}",
            token=seeded_user_token,
        )
