"""docs/08-testing.md's `test_ingest_pipeline` + docs/10-roadmap.md's Phase 3 exit criteria.
Runs against the real deployed `dev` stack — `CWD_INTEGRATION=1 uv run pytest -m integration`
(see `conftest.py` for the env vars it needs).

Asserts `READY`, chunk count, and one hand-checked sentence's rect — **not** vector count. Phase
3's explicit goal is "no embeddings yet" (docs/10-roadmap.md's Phase 3 header); the vector-count
assertion docs/08-testing.md's table describes belongs to this same test's Phase 4 revision, once
`EnsureIndex`/`EmbedAndIndex` exist.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from conftest import ApiHelpers, CognitoConfig

    from common.repo import Repo

pytestmark = pytest.mark.integration

# Hand-checked against e2e/fixtures/five-page.pdf (generated by
# e2e/fixtures/generate_fixtures.py's five_page_pdf): page 3's second sentence, computed by
# running services/ingestion/ingestion/{extract,chunk}.py directly against the fixture and
# reading off the result — see docs/10-roadmap.md's Phase 3 progress log entry for the exact
# derivation.
_EXPECTED_PAGE = 3
_EXPECTED_SENTENCE_TEXT = (
    "Energy consumption per square foot fell to its lowest level since the facility opened."
)
_EXPECTED_RECT = (127.33, 153.29, 471.18, 165.66)
_RECT_TOLERANCE_PT = 1.0


def test_ingest_pipeline_reaches_ready_with_expected_chunks_and_a_hand_checked_rect(
    cognito_config: CognitoConfig, seeded_user_token: str, repo: Repo, api: ApiHelpers
) -> None:
    project_id, document_id = api.upload_fixture(
        cognito_config, seeded_user_token, "five-page.pdf", "application/pdf", name_suffix="ingest"
    )
    try:
        status, body = api.request(
            "POST",
            f"{cognito_config.api_base_url}/projects/{project_id}/documents/{document_id}/ingest",
            token=seeded_user_token,
        )
        assert status == 202, body

        document = api.wait_for_terminal_status(
            cognito_config, seeded_user_token, project_id, document_id
        )
        assert document["status"] == "READY", document.get("statusDetail")
        assert document["pageCount"] == 5
        assert document["ingestion"]["chunkCount"] > 0
        assert document["ingestion"]["ocrPages"] == 0

        pages = repo.list_pages(document_id)
        assert len(pages) == 5
        assert all(p.text_source == "pdf" for p in pages)

        chunks = [c for c in repo.list_chunks(document_id) if c.page_number == _EXPECTED_PAGE]
        assert chunks, f"no chunks found for page {_EXPECTED_PAGE}"
        matching_sentence = next(
            (
                sentence
                for chunk in chunks
                for sentence in chunk.sentences
                if sentence.text == _EXPECTED_SENTENCE_TEXT
            ),
            None,
        )
        assert matching_sentence is not None, (
            f"expected sentence not found among page {_EXPECTED_PAGE}'s chunks"
        )
        assert len(matching_sentence.rects) == 1
        rect = matching_sentence.rects[0]
        for actual, expected in zip(rect, _EXPECTED_RECT, strict=True):
            assert actual == pytest.approx(expected, abs=_RECT_TOLERANCE_PT)
    finally:
        api.request(
            "DELETE",
            f"{cognito_config.api_base_url}/projects/{project_id}",
            token=seeded_user_token,
        )
