#!/usr/bin/env bash
# Reads CDK stack outputs and writes web/.env.{env}, then builds the SPA
# (docs/06-frontend.md#build-and-deploy). Run after a human's `cdk deploy --all` — see
# docs/09-operations.md#deployment for the full sequence.
#
# Usage: ./scripts/build-web.sh [env]   (defaults to "dev")
set -euo pipefail

ENV="${1:-dev}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# `cdk deploy --all --context env=$ENV --outputs-file infra/cdk-outputs.$ENV.json` produces
# this file. It is a build artifact (gitignored), not the source of truth — CDK exports are.
OUTPUTS_FILE="${CWD_OUTPUTS_FILE:-$REPO_ROOT/infra/cdk-outputs.${ENV}.json}"
ENV_FILE="$REPO_ROOT/web/.env.${ENV}"

if [[ ! -f "$OUTPUTS_FILE" ]]; then
  echo "error: outputs file not found at $OUTPUTS_FILE" >&2
  echo "Produce it first with:" >&2
  echo "  cd infra && npx cdk deploy --all --context env=${ENV} --outputs-file cdk-outputs.${ENV}.json" >&2
  exit 1
fi

env_title="$(tr '[:lower:]' '[:upper:]' <<<"${ENV:0:1}")${ENV:1}"
auth_stack="Cwd${env_title}AuthStack"
compute_stack="Cwd${env_title}ComputeStack"
realtime_stack="Cwd${env_title}RealtimeStack"

get_output() {
  local stack="$1" key="$2"
  jq -er --arg s "$stack" --arg k "$key" '.[$s][$k]' "$OUTPUTS_FILE" 2>/dev/null || {
    echo "error: missing output ${stack}.${key} in $OUTPUTS_FILE" >&2
    exit 1
  }
}

user_pool_issuer=$(get_output "$auth_stack" "UserPoolIssuer")
user_pool_domain_url=$(get_output "$auth_stack" "UserPoolDomainUrl")
user_pool_client_id=$(get_output "$auth_stack" "UserPoolClientId")
api_base_url=$(get_output "$compute_stack" "ApiBaseUrl")
events_realtime_domain=$(get_output "$realtime_stack" "EventsRealtimeDomain")
events_http_domain=$(get_output "$realtime_stack" "EventsHttpDomain")
cognito_domain="${user_pool_domain_url#https://}"

cat >"$ENV_FILE" <<EOF
# Generated by scripts/build-web.sh from ${OUTPUTS_FILE#"$REPO_ROOT"/} — do not edit by hand.
VITE_COGNITO_AUTHORITY=${user_pool_issuer}
VITE_COGNITO_DOMAIN=${cognito_domain}
VITE_COGNITO_CLIENT_ID=${user_pool_client_id}
VITE_API_BASE=${api_base_url%/}
VITE_EVENTS_REALTIME_DOMAIN=${events_realtime_domain}
VITE_EVENTS_HTTP_DOMAIN=${events_http_domain}
EOF

echo "Wrote $ENV_FILE"

cd "$REPO_ROOT/web"
# `--mode $ENV` makes Vite load `.env.$ENV` (Vite's built-in per-mode env file convention)
# instead of the `production`/`development` defaults, matching the `.env.{env}` naming this
# script itself writes.
npm run build -- --mode "$ENV"
